# Generated by Django 5.2.7 on 2026-01-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotodeperfil', models.ImageField(blank=True, null=True, upload_to='perfil/imagens/')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
