# Generated by Django 5.2.7 on 2026-02-20 22:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fotodeperfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto de perfil'),
        ),
    ]
