# Generated by Django 5.2.7 on 2026-03-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_perfil_fotodeperfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='perfil',
        ),
    ]
