# Generated by Django 5.2.7 on 2025-11-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('sbrnom', models.CharField()),
                ('username', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=8)),
            ],
        ),
    ]
