# Generated by Django 5.2.7 on 2025-12-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginmodel',
            old_name='senha',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='loginmodel',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='loginmodel',
            name='sbrnom',
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='username',
            field=models.CharField(),
        ),
    ]
