# Generated by Django 5.2.7 on 2026-01-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_senha_loginmodel_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
