# Generated by Django 5.2.7 on 2026-01-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_loginmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
