# Generated by Django 5.2.7 on 2026-01-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='autor',
        ),
    ]
