# Generated by Django 5.2.7 on 2026-01-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_remove_caditmmodel_imagem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caditmmodel',
            name='imagem_item',
            field=models.ImageField(blank=True, null=True, upload_to='produto/imagens'),
        ),
        migrations.DeleteModel(
            name='ImagemProduto',
        ),
    ]
