# Generated by Django 5.2.7 on 2026-01-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_caditmmodel_imagem_item_delete_imagemproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='caditmmodel',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='caditmmodel',
            name='desconto',
            field=models.FloatField(default=0.0, help_text='Desconto em porcentagem (0-100)'),
        ),
    ]
