# Generated by Django 5.2.7 on 2026-01-22 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_caditmmodel_criado_em_caditmmodel_desconto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produto/imagens/')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produto.caditmmodel')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
