# Generated by Django 5.2.7 on 2026-01-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_imagemproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caditmmodel',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='caditmmodel',
            name='imagem_item',
        ),
        migrations.RemoveField(
            model_name='imagemproduto',
            name='imagem',
        ),
        migrations.AddField(
            model_name='caditmmodel',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='caditmmodel',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemproduto',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caditmmodel',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='caditmmodel',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='caditmmodel',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='caditmmodel',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
