# Generated by Django 5.2.7 on 2026-01-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_remove_caditmmodel_desconto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caditmmodel',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
