# Generated by Django 5.2.7 on 2026-01-27 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_produtoimagem_remove_imagemproduto_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='caditmmodel',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='caditmmodel',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='caditmmodel',
            name='imagem_item',
            field=models.ImageField(blank=True, null=True, upload_to='produto/imagens'),
        ),
        migrations.AlterField(
            model_name='caditmmodel',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='caditmmodel',
            name='desconto',
            field=models.FloatField(default=0.0, help_text='Desconto em porcentagem (0-100)'),
        ),
        migrations.AlterField(
            model_name='caditmmodel',
            name='descricao',
            field=models.TextField(default='Descrição do item'),
        ),
        migrations.AlterField(
            model_name='caditmmodel',
            name='nome',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='caditmmodel',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produto/imagens/')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produto.caditmmodel')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.DeleteModel(
            name='ProdutoImagem',
        ),
    ]
