# Generated by Django 5.2.7 on 2026-01-27 21:33

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_produto_remove_caditmmodel_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caditmmodel',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caditmmodel',
            name='desconto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='caditmmodel',
            name='imagem_item',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagem_principal'),
        ),
        migrations.AlterField(
            model_name='imagemproduto',
            name='imagem',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem'),
        ),
    ]
