# Generated by Django 5.2.7 on 2026-03-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_alter_caditmmodel_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caditmmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
