# Generated by Django 5.2.7 on 2026-03-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_alter_caditmmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='caditmmodel',
            name='contato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
