# Generated by Django 5.2.7 on 2026-03-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_caditmmodel_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='caditmmodel',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
