# Generated by Django 5.2.7 on 2026-02-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmusersort',
            name='tipo_user',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Vendedor', 'Vendedor'), ('Administrador', 'Administrador')], default='Comprador', max_length=20),
        ),
    ]
