# Generated by Django 5.2.7 on 2026-02-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_nmusersort_tipo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmusersort',
            name='tipo_user',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Vendedor', 'Vendedor')], default='Cliente', max_length=20),
        ),
    ]
