# Generated by Django 5.2.7 on 2026-03-02 18:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_nmusersort_tipo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nmusersort',
            old_name='tipo_user',
            new_name='cargo',
        ),
        migrations.AddField(
            model_name='nmusersort',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nmusersort',
            name='fotodeperfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto de perfil'),
        ),
    ]
