# Generated by Django 5.2.7 on 2026-03-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_rename_tipo_user_nmusersort_cargo_nmusersort_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nmusersort',
            name='user',
        ),
    ]
