# Generated by Django 5.2.7 on 2026-03-02 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_remove_nmusersort_user_nmusersort_usersort'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='nmusersort',
            old_name='cargo',
            new_name='tipo_user',
        ),
        migrations.RemoveField(
            model_name='nmusersort',
            name='usersort',
        ),
        migrations.AddField(
            model_name='nmusersort',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
