# Generated by Django 5.2.7 on 2026-03-02 23:30

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_rename_cargo_nmusersort_tipo_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nmusersort',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='nmusersort',
            name='fotodeperfil',
        ),
        migrations.CreateModel(
            name='UserMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotodeperfil', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto de perfil')),
                ('bio', models.TextField(blank=True, null=True)),
                ('tipo_user', models.CharField(default='Cliente', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
