# Generated by Django 5.2.7 on 2026-03-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_userendereco_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermod',
            name='contatowspp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
