# Generated by Django 5.2.7 on 2025-12-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadItmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField()),
                ('desc', models.TextField()),
                ('username', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=8)),
            ],
        ),
    ]
